/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vinneg_natpoacher_MouseCursor */

#ifndef _Included_vinneg_natpoacher_MouseCursor
#define _Included_vinneg_natpoacher_MouseCursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vinneg_natpoacher_MouseCursor
 * Method:    getCursor
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_vinneg_natpoacher_MouseCursor_getCursor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
