/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vinneg_natpoacher_MouseCursor */

#ifndef _Included_vinneg_natpoacher_MouseCursor
#define _Included_vinneg_natpoacher_MouseCursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vinneg_natpoacher_MouseCursor
 * Method:    getCursorHash
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_vinneg_natpoacher_MouseCursor_getCursorHash
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
